dist: trusty
language: node_js
node_js:
    - "10"
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
install:
    - cd frontend; yarn install
script:
    - cd frontend; yarn run test
cache:
    yarn: true
